### PR TITLE
Adding support for output device switching

### LINKED ISSUE #46: Implement output device selection mode
**Is your feature request related to a problem? Please describe.**
Switching output devices is not supported and needs to be done via windows.

**Describe the solution you'd like**
A new mode where you can switch between output audio devices by rotating the knob.

**Describe alternatives you've considered**

**Additional context**

### LINKED ISSUE #111: Implement output device check
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I change the output device to my headphones, but the Maxmix is still controlling the Speakers output device. I need to unplug the Maxmix from the PC and plug it back in for Maxmix to start working with my headphones output.

**Describe the solution you'd like**
Implement an output device check in the Maxmix software

**Describe alternatives you've considered**
The alternative is being able to switch between outputs manually (issue #46 ) But it would be better if the change of the output device would be automatic.

### PR DESCRIPTION
**Pull request by t3knomanzer**
## Issues
 - Resolves #46, #111

## Description
I am implementing being able to switch output devices from the controller.  
I made it part of Master mode since it made sense for it to be there and it's consistent with the rest of the application.  

Master mode now has a navigation screen where you can scroll through the different output devices.  
Tapping in navigation mode will select the device and take you to the volume edit screen.   
Double-tapping in edit mode will mute the selected device.  
The behavior is consistent with Application and Game modes. 

## Implementation
**This is a very rough implementation, I wanted to have it all there and working to see what it'd take.**

Observed behavior:
If an application is set to use the default output device, references to the audio session will be created in output devices as you switch to them. Switching the default output device won't destroy the reference to the session in the other devices, therefore references to the same session can exist in multiple devices.
Exiting the application will only trigger the event in the current default output device leaving null references in other devices.

If the application specifies a particular output device to use, the session will be created in and only exist under that device unless the device is disconnected, in which case the session is created in the new active device. Once the device is reconnected the session is transferred back to it. Destruction of sessions behaves just like described above.

This makes the current object oriented implementation rather cumbersome since AudioSessions exist inside AudioDevices.  
This means we would need to keep AudioSessions in sync across AudioDevices.

To overcome this, I switched back to the original data oriented approach proposed by @XScorpion2. AudioSessions are managed by the AudioSessionManager instead of the AudioDevices.

There is currently a ton of redundant code caused by the split of devices and sessions, even though the partially share a common interface and code could be reused. This is going to be revisited.

I wasn't able to find a way to easily switch the default endpoint. CSCore does not seem to support it and the methods I have found online are rather dirty. Any help on that front would be appreciated.

## Risks
This feature required some pretty major changes. It will have to be deeply tested but there are bugs that I just can't reproduce in my PC so it will need the help from the whole team.

## Types of changes
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [X] Requested changes are in a branch
- [ ] Compiled and tested requested changes on target hardware (PC, device)
- [X] Updated the documentation, if necessary
- [X] Updated the LICENSES file, if necessary
- [X] Reviewed the [guidelines for contributing](../CONTRIBUTING.md) to this repository

### CODE REVIEW

**Review by XScorpion2 — APPROVED** [review]

**Comment by t3knomanzer** [comment]
@quadbyte @SchemingWeasels I have a question in regards to the expected behavior for this.

Do we expect the device to list all the applications across all output devices, or just the ones that belong to the current default device?

For example, if you have headphones and speakers, are we expecting that you may have something playing in each device at the same time and that you'd want to be able to control the volume of those applications independently? Or are we expecting only one device to be active at a time?

**Comment by SchemingWeasels** [comment]
I think only the ones belonging to the selected device. Some programs have multiple sessions across multiple devices. If you list them all you will have duplicates with no indication for which belongs to which output right?

**Comment by t3knomanzer** [comment]
Right, that’s actually taken care of. I updated the grouping code and we treat sessions across multiple devices as part of the same group so they get synchronized. 

There are other things that are definitely tricky to implement but I can look into what it takes. 

I think the feedback I’m looking for is more from a user point of view. 
Everyone uses their computer for different things and in different ways so I don’t know if having all sessions across all devices available adds value, if there is a good use case for it. It isn’t something I need myself but I can imagine there may be for some people?

**Comment by t3knomanzer** [comment]
This is ready for testing and review when you guys have a minute. As mentioned, it's quite a lot of changes so diffing the code may not be feasible.  
I am intentionally not handling disconnection, connection and re-connection of devices on the fly since it was causing issues. I think it's fair to have an initial release where we don't handle those cases and expect the user to restart the application in those events. We can add support for that later.  
You will see that on the firmware side, since we have 2 separate arrays for devices and sessions and the arrays need to be of a fixed size, we need to choose between how much we allocate to devices vs apps which is not good.  
That's exactly why I think we should implement a circular buffer, so we only need to hold 3 apps and 3 devices at a time in memory so we can support an infinite number.

Let me know what you think!

**Comment by ItsLemmy** [comment]
Haven't checked the code yet. But why do we need the arrays to be of a fixed side ?

**Comment by t3knomanzer** [comment]
We can do dynamic allocation but just to keep things simple as far as memory management.
We were allocating the sessions array to a fixed size before, based on how much memory the Item structure takes and what we have available. We now have 2 arrays, one for devices and one for sessions so that number needs to be split. There is wasted memory if we allocate 3 devices and we only have 2, etc. But considering that once we implement the circular buffer this is going away...  
Does that make sense? What do you propose?

**Comment by XScorpion2** [comment]
Little bit of testing:

- Having multiple devices all named "Speakers (Device Name)" per windows standard is limiting on the device screen size. Might be worth extracting device name out of the parenthesis section and just use that for the display name.
- I've got 3 speaker devices and System Sounds are not grouping up across all the devices. I end up with 2, 1 group of 2 from the non-default device, and 1 group of 1 from the default device. 
- One of my active audio sessions is missing (Firefox) with these changes. It's not grouped up into any other session. 

Debugging the firefox one now.

**Comment by XScorpion2** [comment]
- I've got 3 speaker devices and System Sounds are not grouping up across all the devices. I end up with 2, 1 group of 2 from the non-default device, and 1 group of 1 from the default device.

This is due to the System Sounds returning the file path for Explorer.exe for the main module filename if it is the session for the default device, but it doesn't if it is for the non-default device. So probably need a better method for handling this case.

**Comment by t3knomanzer** [comment]
On it!

**Comment by XScorpion2** [comment]
- One of my active audio sessions is missing (Firefox) with these changes. It's not grouped up into any other session.

It's found, and sent to device, I guess this is due to a display limit? Not sure what the current limits are. With the duplicated System Sounds I would be at 3 devices, 6 sessions, Firefox being the 7th session.

**Comment by t3knomanzer** [comment]
@XScorpion2 Can you try again? See if this fixes the system sounds groupping and the device naming.

**Comment by XScorpion2** [comment]
@t3knomanzer New device display name is perfect, the ProcessID for all system sounds is now 0, however the GetSessionGroupId function in AudioSessionService.cs does not check for IsSystemSound and only validates against fileName. Need to add a check there to wrap that up.

**Comment by XScorpion2** [comment]
Something like this: 

```
        private int GetSessionGroupId(IAudioSession session)
        {
            var audioSession = session as AudioSession;
            if (audioSession.IsSystemSound)
                return audioSession.ProcessID;

            var fileName = audioSession.Process.GetMainModuleFileName();
            if (!string.IsNullOrEmpty(fileName))
                return fileName.GetHashCode();

            return audioSession.ProcessID;
        }
```

**Comment by XScorpion2** [comment]
Also validated that Firefox now shows up with less active sessions, so guess I'm hitting the device memory limit.

**Comment by t3knomanzer** [comment]
Ok sure, thank you!

**Comment by t3knomanzer** [comment]
Done! Yeah we are limiting it to 5 sessions and 3 devices. Should be fixed as soon as we implement the circular buffer.

**Review by XScorpion2 — APPROVED** [review]

**Comment by t3knomanzer** [comment]
Thanks for the approval, I'll wait for @quadbyte and @SchemingWeasels to test it quickly before merging it into master.

**Comment by t3knomanzer** [comment]
@quadbyte Has been testing it all afternoon and seems to be good.

**Pull request merged**
