### PR TITLE
Added Support for LCD and Potentiometer

### PR DESCRIPTION
**Pull request by Technologyman00**
Initial push of adding support with a LCD (with Hitachi HD44780 driver Parallel Mode) and a Potentiometer. This is just so I could build a prototype with parts I already had on hand.

I was not sure how I should do this, so based off I cannot create more branches on GitHub, I created another folder in Embedded containing the changes allowing a LCD, a Button, and a Potentiometer. I thought this could be useful for others that wanted to use similar parts and I didnt want it to get lost in my Repository, so please let me know if this not the way you would like this code to be added. 
IMG_20200807_224248
IMG_20200807_224340
IMG_20200807_224359
IMG_20200807_224409
IMG_20200807_224415
IMG_20200807_224452
IMG_20200807_224459

### CODE REVIEW

**Comment by SchemingWeasels** [comment]
Thanks for the contribution.
Do read the contribution guidelines as well for future PRs.

I don’t think the file structure is ideal, and if we proceed with splitting into a different directory, there’s is a bunch of unused code from the OLED display.

I can clean this up but I’ll wait for @t3knomanzer if he wants to proceed with supporting this officially at this moment.

**Comment by Technologyman00** [comment]
Hello @SchemingWeasels,

I probably should have wrote more above, but some of the redundant code for the OLED is still there so incase you have an encoder and an LCD you can just replace the Display.ino and Logo.h or if you have potentiometer and a OLED you can replace the Maxmix.ino and everything should still work normally. I don't think this is the best way to do this, but for someone with almost zero coding experience should be able to easily swap files.

**Comment by t3knomanzer** [comment]
Hey @Technologyman00 ,
Let me start by saying that this is an awesome contribution, thanks lot for doing this.

As far as the implementation I completely agree with @SchemingWeasels, It's not very ideal.

The way I would suggest to implement this is by creating a DisplayLcd.ino and LogoLcd.ino.  
Then I would create a #define SCREEN_LCD in Config.h.  
In would then wrap the code in Display.ino, DisplayLcd.ino in an  #ifndef/#ifdef SCREEN_LCD.

Also the Adafruit_SSD1306* display; would need to change to
```
#ifndef SCREEN_LCD  
Adafruit_SSD1306* display;  
#else  
LiquidCrystal* display;
#endif
```

The idea is that basically since it's just a refactor of the code inside the functions in display.ino, we should be able to swap them seamlessly based on a define.

Duplicating the entire code means maintaining and testing 2 identical branches for no reason.

Does that make sense?
Also I would strongly suggest that you move your changes to a branch instead of commiting and requesting the PR from master. 

What do you think?

**Comment by Technologyman00** [comment]
Hello @t3knomanzer,

Yeah that makes sense.  I am studying Mechanical Engineering, so I probably would come back with questions as I go about implementing this. 

To confirm this won't cause tons of extra usage of the arduino's storage? I am not super sure how the compiler works and what it all grabs.

**Comment by Technologyman00** [comment]
Also should I close this and then re-submit later?

**Comment by t3knomanzer** [comment]
@Technologyman00 No problem at all, we're all are happy to help here!
#defines are what's called pre-processor directives so the code that's ignored as a result of a define is not even included in the compiled firmware.  

https://www.arduino.cc/reference/en/language/structure/further-syntax/define/

**Comment by t3knomanzer** [comment]
What I would do is:
* Copy the Display.ino and Logo.h that you've modified somewhere else in your computer and rename them to DisplayLcd.ino and LogoLcd.h
* Force sync the repo from master to wipe all your changes.  
* Create a new branch.
* Copy the 2 files back to the repository directory so that those 2 files are the only changes you have.
* Commit
* Create a new PR from that branch to master.

**Comment by Technologyman00** [comment]
Thank you!

**Pull request closed without merging**
