### PR TITLE
Adjusted SerialPort configuration to activate RTS and DTS lines for ATmega32U4 based Arduino boards

### PR DESCRIPTION
**Pull request by pcky**
## Description
This will solve communication issues with ATmega32U4 based Arduino boards like Sparkfun's Pro Micro and it's clones.

## Types of changes
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] Compiled and tested requested changes
- [ ] Updated the documentation, if necessary
- [ ] Updated the LICENSES file, if necessary
- [ ] Reviewed the [guidelines for contributing](../CONTRIBUTING.md) to this repository
- [ ] Requesting to **pull a topic/feature/bugfix branch**

## Further comments

If accepted, this will open the Maxmix plattform to ATmega32U4 based Arduino boards. These do also feature support for other USB device profiles e.g. HID keyboard & multimedia control. So in the future Maxmix could even provide a portable/compatibility mode that offers limited multimedia control on any Computer without the need for drivers or software. More info about the USB HID features: https://github.com/NicoHood/HID

### CODE REVIEW

**Comment by t3knomanzer** [comment]
Thanks a lot for the contribution, that's great!
Could you squash the 2 commits together before merging?

**Comment by t3knomanzer** [comment]
Have you actually tested the changes with a maxmix device? 
It's causing mine to continuously reboot.

**Comment by pcky** [comment]
> Have you actually tested the changes with a maxmix device?
> It's causing mine to continuously reboot.

Ha, you are right. I totally forgot that the Nano resets on DTR high. So unfortunately this change is not compatible with both of the Arduinos. At least not without further changes to the Windows app like a board selector in the app settings . 

Sorry for the trouble!

**Comment by t3knomanzer** [comment]
Oh no trouble at all! You made a very good point. I would actually make this into a feature request to make sure the 
 information is captured unless you want to do the extra work.

**Pull request closed without merging**
