### PR TITLE
Added support for hardware interrupts

### LINKED ISSUE #123: Use interrupts to handle encoder positioning
**Is your feature request related to a problem? Please describe.**
Currently, encoder tracking is polled in the main loop. Moving to hardware-based interrupts could improve performance and the feel of the device as a whole.

This could improve support for various encoders as well.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Libraries in consideration :
- [Encoder](https://github.com/PaulStoffregen/Encoder)
- [ClickEncoder](https://github.com/0xPIT/encoder/tree/arduino)

- No library at all. Extra unused features provided by the libraries is just bloat and we could be better off writing custom functions instead.

### PR DESCRIPTION
**Pull request by SchemingWeasels**
## Issues
 - Closes #123

## Description
Moved to hardware interrupts for encoder step handling. As such, pin assignments have to be changed. **This is a breaking change.**
Encoder data pins have to be on D2 and D3 for hardware interrupts! (Swap them if your knob is opposite to what you are used to, lefty version perhaps? 😉 )

Added support for exponential acceleration (squared function) with configurable acceleration values. Only 1 variable controls the feel.
Added support for half stepping directly in Config.h.
Added PaulStoffregen's Encoder library directly into the repo and removed the old library.
Button clicks are still handled the same way.

## Types of changes
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [X] Requested changes are in a branch
- [X] Compiled and tested requested changes on target hardware (PC, device)
- [X] Updated the documentation, if necessary
- [ ] Updated the LICENSES file, if necessary
- [X] Reviewed the [guidelines for contributing](../CONTRIBUTING.md) to this repository

## Further comments

Do try out this version. Let me know how it feels to use. I find it to be a lot more consistent on mine (but mine is a much much smaller knob). Try various acceleration values it doesn't work for you and let me know if the larger knob has a nicer default acceleration divisor.

### CODE REVIEW

**Comment by SchemingWeasels** [comment]
Also, I could use some help with the licenses. I have no idea what Paul Stoffregen's license.. erm... 'type' is. In Encoder.h it basically says fully open source. But I'm not sure what to categorize it under for the licenses file.

Edit: I just found a bug with the acceleration when you scroll fast when you are already at 100 volume. I'll take a look tomorrow, but if anyone has an idea why this is happening let me know.

**Comment by SchemingWeasels** [comment]
It was an int overflow. Rookie mistake 😄

**Comment by t3knomanzer** [comment]
Hey @SchemingWeasels,

So I have some bad news... the HW pin interrupts are what I was originally using before the project was even released.   
I had to move away from those because there is not enough space physically between the D2, D3 pins and the top of the enclosure.   
It just so happens that they are right where the top dips down.   
That’s the only reason I had to switch to software based approach. Design flaw...

So as awesome as this contribution is, we’re gonna have to find another way. 😔

So sorry about that buddy.

**Comment by SchemingWeasels** [comment]
> there is not enough space physically between the D2, D3 pins and the top of the enclosure

Ahh. Makes sense why I didn't spot this 😄. Yea I understand there's no way around this without either changing the enclosure or the build process (soldering hookup wires directly to the nano). 

I'll test with the library's polling mode and report back. I doubt it'll be any better than the previous solutions. I think timer ISR is the way forward.

Just wondering, which pins, if any, are accessible? Just everything on the analog side?

**Comment by ItsLemmy** [comment]
Oh damn this is really unfortunate. 

I guess switching Arduino is also not an option ?
The Teensy-LC is cheap, as way more memory, more processing power, support interrupts on most of it pins, and comes in a smaller form factor.
Maybe the extra memory and CPU could be useful in the long run to improve the experience : display, scrolling, etc..

Please don't take it the wrong way, I can also perfectly understand why you would rather not :)

**Comment by t3knomanzer** [comment]
> Just wondering, which pins, if any, are accessible? Just everything on the analog side?

The entire analog side and D12 to D8 on the opposite side. 


https://maxmixproject.com/build-soldering/

**Comment by t3knomanzer** [comment]
> Oh damn this is really unfortunate. 
> 
> 
> 
> I guess switching Arduino is also not an option ?
> 
> The Teensy-LC is cheap, as way more memory, more processing power, support interrupts on most of it pins, and comes in a smaller form factor.
> 
> Maybe the extra memory and CPU could be useful in the long run to improve the experience : display, scrolling, etc..
> 
> 
> 
> Please don't take it the wrong way, I can also perfectly understand why you would rather not :)
> 
> 
> 
> 
> 
> 
> 
> 

Yeah switching boards is something we should definitely consider but I wouldn’t do it  yet. I think we should continue to mature and evolve the project with the current hardware.   


Take into account there is a user base that has invested time and money into building the hardware for this.l and the project is just 2 months old. 

Switching boards now would mean having to support 2 versions and we do not have enough contributors to do that efficiently. 

I think that once the project has matured enough, we should plan a 2.0 release that incorporates user feedback not just on the software side but also on the hardware. Extra buttons, bigger screen, etc. at that point we release a new redesigned enclosure, new hardware, build instructions, etc. Support 1.0 but stop adding new features and slowly drop support and transition to 2.0

Does that make sense?

**Comment by SchemingWeasels** [comment]
Ok I'll be closing this PR for now. I got a working version using Timer1. Will be out later today. Thanks for the feedback!

**Pull request closed without merging**
