### PR TITLE
Keep user settings after version update

### LINKED ISSUE #155: Application settings not kept between updates
**Guidelines**
- [X] I have reviewed the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

**Describe the bug**
User settings are not being maintained between application updates

**To Reproduce**
1. Install a version
2. Run the app and change the settings'
3. Update to a newer version
4. Run the app and observe how the settings are reset to default.

**Expected behavior**
User changed settings should be maintained between application updates.

**Screenshots**

**System information:**
 - OS version: [e.g. Windows 10 x64 1008]
 - Firmware version: [e.g 1.0.4]

**Additional context**
https://docs.microsoft.com/en-us/dotnet/desktop/winforms/advanced/application-settings-overview?view=netframeworkdesktop-4.8

### PR DESCRIPTION
**Pull request by samgaudr**
## Issues
 - Fixes #155

## Description
When application is updated, setting from the older version are migrated and then used for the current version.

## Types of changes
_Put an `x` in the boxes that apply_

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [X] Requested changes are in a branch
- [X] Compiled and tested requested changes on target hardware (PC, device)
- [X] Updated the documentation, if necessary
- [X] Updated the LICENSES file, if necessary
- [X] Reviewed the [guidelines for contributing](../CONTRIBUTING.md) to this repository

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by XScorpion2 — APPROVED** [review]
Code looks good, will pull and test shortly

**Comment by XScorpion2** [comment]
@samgaudr can you fix your PR by merging master and fixing the merge conflict?

**Comment by samgaudr** [comment]
@XScorpion2  Yep, Done!

**Comment by XScorpion2** [comment]
ty

**Pull request merged**
