### PR TITLE
Sturdy com

### LINKED ISSUE #110: Desktop software CPU usage
**Describe the bug**
MaxMix desktop software is constantly using about 16% of my i7-4790K CPU.

**To Reproduce**
1. Launch MaxMix 1.0 without any MaxMix device connected.
2. Launch Windows TaskManager.
3. Check CPU usage for MaxMix software in the TaskManager.

**Expected behavior**
Desktop software should use less CPU. 

**Screenshots**
Taskmgr_833e5AI5PA

**Desktop :**
 - OS: Windows 10 Pro.
 - Version: 19.09

**Additional context**
Have not inspected the code yet, but I suppose the software is sending handshake too often ?

### PR DESCRIPTION
**Pull request by ItsLemmy**
## Issues
The communication between the host app and device was not very reliable. We received a few sentry crash everyday related to multi-threading problems.
 - Also fixes issue #110

## Description
I refactored the DiscoveryService into the CommunicationService.  Tried to simplify things so that they all run in a single thread. Added a lot of debug messages to help find the edge cases. 
The communication service is now more reliable and did never crash on me, even if an ACK is missed. Worst case scenario it will reconnect.

## Types of changes
- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] Requested changes are in a branch
- [x] Compiled and tested requested changes on target hardware (PC, device)
- [x] Reviewed the [guidelines for contributing](../CONTRIBUTING.md) to this repository

## Further comments
At first I tried to fix the existing code to wipe the nasty bug we've seen on sentry. But the fact that we had separate services and they were start and stopped all over the place made the debug process almost impossible.  Multi-threading debugging is always painful... After spending 6 hours of debugging I decided it would be more efficient to refactor things.

### CODE REVIEW

**Comment by SchemingWeasels** [comment]
Not too familiar with the backend framework. I can help by changing the build number and running for a few days, then it’ll show in sentry if there’s crashes.

**Comment by t3knomanzer** [comment]
If you want to test it @SchemingWeasels, 
the crash happens when unplugging and plugging back the device while the app is running. Doesn’t happen always either. 

We can see the machine name in Sentry and the versión if you run from visual studio is 0.9.0.0 so no need to change it. 

I’m gonna run it too see if I can get it to crash. 

Thanks a ton everyone!

**Comment by ItsLemmy** [comment]
Just noticed it doesn't quit nicely. Will fix soon.

**Comment by t3knomanzer** [comment]
I've been testing thoroughly for about 30 minutes running from VS and haven't been able to crash it so far.

**Comment by t3knomanzer** [comment]
Just testing the Discord webhook here.

**Comment by t3knomanzer** [comment]
Testing discord integration from PR comment.

**Review by t3knomanzer — APPROVED** [review]

**Pull request merged**
