### PR TITLE
Com Fix for Sentry' s issues

### PR DESCRIPTION
**Pull request by ItsLemmy**
## Issues
 - Fixes a regression : sentry bug #MAXMIX-X where we receive data from a serial port while closing it.
- Fix another sentry issue #MAXMIX-W where we receive unknown command from the device.

## Types of changes
- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist
- [x] Requested changes are in a branch
- [x] Compiled and tested requested changes on target hardware (PC, device)
- [x] Reviewed the [guidelines for contributing](../CONTRIBUTING.md) to this repository

### CODE REVIEW

**Comment by t3knomanzer** [comment]
Which issue is 1867402731?

**Comment by ItsLemmy** [comment]
Updated the description

**Comment by t3knomanzer** [comment]
Ok. I'm assuming this is a fix for MAXMIX-X by the looks of it.

**Comment by ItsLemmy** [comment]
Yep X & W, sorry I just noticed those weird issues number.

**Comment by t3knomanzer** [comment]
Thanks a lot for this. I'll pull latest and test it.

**Pull request merged**
