### PR TITLE
Added support for infinite scrolling

### PR DESCRIPTION
**Pull request by SchemingWeasels**
## Issues
 - _Attempt to Resolve_ # 62

## Description
Added support for infinite scrolling on the embedded side.
Requires support on the desktop app.

## Types of changes
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [X] Compiled and tested requested changes
- [X] Updated the documentation, if necessary
- [X] Updated the LICENSES file, if necessary
- [X] Reviewed the [guidelines for contributing](../CONTRIBUTING.md) to this repository
- [X] Requesting to **pull a topic/feature/bugfix branch**

## Further comments
Another element has been added to the settings struct (default true) for infinite scrolling. I have added it as the 4th index of the settings update packageBuffer. 

The feature works as is but there is no way to turn it off without updating the desktop app or compiling your own arduino bin.

I don't really know how to work on the desktop app. Maybe a point in the right direction of where I should start would be great @t3knomanzer .

### CODE REVIEW

**Comment by SchemingWeasels** [comment]
continuousScroll = 1 for infinite scroll, 0 for standard scroll. default = 1

**Comment by t3knomanzer** [comment]
Hi,
Taking a look at this now. Would you mind squashing the 4 commits? 
I would also strongly recommend that you move your changes to a branch.

Thank you!

**Comment by SchemingWeasels** [comment]
I think I have made quite a mess of my fork.... I have branched the changes and reverted my master branch. Should I close this pull request and open another one from that branch?

**Comment by t3knomanzer** [comment]
Sure yeah, no problem! :D

**Pull request closed without merging**
